-- Create deal_submissions table for public submissions queue
CREATE TABLE IF NOT EXISTS deal_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name TEXT NOT NULL,
  venue_suburb TEXT,
  title TEXT NOT NULL,
  description TEXT,
  price_cents INT,
  day_of_week INT CHECK (day_of_week BETWEEN 0 AND 6),
  start_time TIME,
  end_time TIME,
  contact TEXT,
  source TEXT DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  approved_by TEXT
);

-- Enable Row Level Security
ALTER TABLE deal_submissions ENABLE ROW LEVEL SECURITY;

-- Policy: Public can insert submissions
CREATE POLICY "public_insert_submissions" 
  ON deal_submissions
  FOR INSERT 
  TO public 
  WITH CHECK (true);

-- Policy: Everyone can read submissions (for admin moderation page)
CREATE POLICY "read_submissions" 
  ON deal_submissions
  FOR SELECT 
  USING (true);

-- Index for efficient queries
CREATE INDEX idx_deal_submissions_approved_at ON deal_submissions(approved_at);
CREATE INDEX idx_deal_submissions_created_at ON deal_submissions(created_at DESC);

